Transform: AWS::Serverless-2016-10-31

Parameters:
  CognitoRegion:
    Type: String
    Default: us-west-2

  CognitoUserPoolId:
    Type: String
    Description: User Pool ID (e.g. us-west-2_abc123)

  CloudFrontOrigin:
    Type: String
    Description: CORS Origin
    # Example: "'http://localhost:5173'"
    Default: "'http://localhost:5173'"

  StageName:
    Type: String
    Default: Dev

Resources:
  HttpApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors:
        AllowOrigin: !Ref CloudFrontOrigin
        AllowHeaders: "'Authorization,Content-Type'"
        AllowMethods: "'GET,OPTIONS'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub arn:aws:cognito-idp:${CognitoRegion}:${AWS::AccountId}:userpool/${CognitoUserPoolId}
            IdentitySource: method.request.header.Authorization
        # DefaultAuthorizer: CognitoAuthorizer

  UsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "${AWS::StackName}-users"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AuthFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        Minify: true
        Target: "node20"
        Sourcemap: true
    Properties:
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: ../auth-lambda
      Timeout: 5
      Environment:
        Variables:
          ALLOWED_ORIGIN: !Ref CloudFrontOrigin
          USERS_TABLE: !Ref UsersTable
      Events:
        MeEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref HttpApi
            Path: /me
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

Outputs:
  ApiUrl:
    Description: API Gateway Invoke URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
