AWSTemplateFormatVersion: "2010-09-09"
Description: FreeAppAWS frontend static site hosting (S3 + CloudFront, SPA-ready) using OAC

Parameters:
  BucketName:
    Type: String
    Description: S3 bucket name for hosting the React build

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        # IMPORTANT: allow a (non-public) bucket policy for CloudFront
        BlockPublicPolicy: false
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: FreeAppAWS-OAC
        Description: OAC for CloudFront to securely access S3 origin
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: FreeAppAWS frontend distribution
        DefaultRootObject: index.html
        Origins:
          - Id: FrontendOrigin
            # REST endpoint, not website endpoint
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref CloudFrontOAC
        DefaultCacheBehavior:
          TargetOriginId: FrontendOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ["GET", "HEAD"]
          CachedMethods: ["GET", "HEAD"]
          ForwardedValues:
            QueryString: false
          MinTTL: 0
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100
        HttpVersion: http2

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontReadViaOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            # IMPORTANT: use the actual bucket ARN, not just the parameter
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                # CloudFront distribution ARN
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

Outputs:
  BucketName:
    Description: Name of the S3 bucket hosting the static site
    Value: !Ref BucketName

  CloudFrontURL:
    Description: CloudFront URL for the hosted React app
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
